apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: log-storage
  volumes:
  - name: log-storage
    persistentVolumeClaim:
      claimName: claim-log-1
